### ISSUE TITLE
To have the generated CHANGELOG file as markdown file

### ISSUE THREAD

**Issue by johnchan-accelo** [cebjyre/changelog-next#12]
Currently, the generated CHANGELOG file is generated as a text file, it will be great if we could get it generated as a markdown file (CHANGELOG.md).

**Comment by cebjyre** [comment]
@johnchan-accelo Would you be happy if that was done as a command line option (ie instead of the `version` script being `changelog-next && git add next-changelog.tmpl CHANGELOG`, you'd be able to have something like `changelog-next -o CHANGELOG.md && git add next-changelog.tmpl CHANGELOG.md`)

**Comment by johnchan-accelo** [comment]
> @johnchan-accelo Would you be happy if that was done as a command line option (ie instead of the `version` script being `changelog-next && git add next-changelog.tmpl CHANGELOG`, you'd be able to have something like `changelog-next -o CHANGELOG.md && git add next-changelog.tmpl CHANGELOG.md`)

Yeah that should work fine too
